//! Embed vendored RuboCop gem config YAML into the binary.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("src/resources/gem_configs").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir
            .join("src/resources/gem_configs_manifest.json")
            .display()
    );
    write_embed_rs(
        &manifest_dir.join("src/resources/gem_configs"),
        &PathBuf::from(env::var("OUT_DIR").unwrap()).join("gem_configs_embed.rs"),
    );
}

fn write_embed_rs(configs: &Path, dest: &Path) {
    let entries = collect_entries(configs);
    let mut code = String::from(
        "// @generated by build.rs — do not edit.\n\
         pub static FILES: &[(&str, &str)] = &[\n",
    );
    for (key, abs) in &entries {
        let abs_str = abs.to_str().expect("utf-8 path");
        code.push_str(&format!("    ({key:?}, include_str!({abs_str:?})),\n"));
    }
    code.push_str("];\n");
    fs::write(dest, code).expect("write gem_configs_embed.rs");
}

fn collect_entries(root: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    if !root.is_dir() {
        return out;
    }
    walk(root, root, &mut out);
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, out);
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("yml") {
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .expect("under gem_configs")
            .to_string_lossy()
            .replace('\\', "/");
        out.push((rel, path));
    }
}
