//! Embed vendored RuboCop gem config YAML into the binary.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let configs = manifest_dir.join("src/resources/gem_configs");
    let manifest = manifest_dir.join("src/resources/gem_configs_manifest.json");
    println!("cargo:rerun-if-changed={}", configs.display());
    println!("cargo:rerun-if-changed={}", manifest.display());
    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("gem_configs_embed.rs");
    write_embed_rs(&configs, &manifest, &out);
}

fn write_files_table(code: &mut String, configs: &Path) {
    code.push_str(
        "// @generated by build.rs — do not edit.\n\
         pub static FILES: &[(&str, &str)] = &[\n",
    );
    for (key, abs) in collect_entries(configs) {
        let abs_str = abs.to_str().expect("utf-8 path");
        code.push_str(&format!("    ({key:?}, include_str!({abs_str:?})),\n"));
    }
    code.push_str("];\n\n");
}

fn write_same_as_table(code: &mut String, manifest: &Path) {
    code.push_str("/// (gem, lock_version, vendored_version) when YAML is byte-identical.\n");
    code.push_str("pub static SAME_AS: &[(&str, &str, &str)] = &[\n");
    for (gem, from, to) in same_as_entries(manifest) {
        code.push_str(&format!("    ({gem:?}, {from:?}, {to:?}),\n"));
    }
    code.push_str("];\n");
}

fn write_embed_rs(configs: &Path, manifest: &Path, dest: &Path) {
    let mut code = String::new();
    write_files_table(&mut code, configs);
    write_same_as_table(&mut code, manifest);
    fs::write(dest, code).expect("write gem_configs_embed.rs");
}

fn push_same_as_gem(gem: &str, meta: &serde_json::Value, out: &mut Vec<(String, String, String)>) {
    let Some(map) = meta.get("same_as").and_then(|s| s.as_object()) else {
        return;
    };
    for (from, to) in map {
        let to = to
            .as_str()
            .unwrap_or_else(|| panic!("same_as target for {gem}/{from} must be a string"));
        out.push((gem.to_string(), from.clone(), to.to_string()));
    }
}

fn same_as_entries(manifest: &Path) -> Vec<(String, String, String)> {
    let raw = fs::read_to_string(manifest).unwrap_or_else(|e| {
        panic!("read {}: {e}", manifest.display());
    });
    let v: serde_json::Value = serde_json::from_str(&raw).unwrap_or_else(|e| {
        panic!("parse {}: {e}", manifest.display());
    });
    let gems = v
        .get("gems")
        .and_then(|g| g.as_object())
        .unwrap_or_else(|| panic!("{}: missing gems object", manifest.display()));
    let mut out = Vec::new();
    for (gem, meta) in gems {
        push_same_as_gem(gem, meta, &mut out);
    }
    out.sort();
    out
}

fn collect_entries(root: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    if root.is_dir() {
        walk(root, root, &mut out);
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, out);
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("yml") {
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .expect("under gem_configs")
            .to_string_lossy()
            .replace('\\', "/");
        out.push((rel, path));
    }
}
